; ------------------------------------------------------------------------------
; LedStripPixelControl - PlatformIO Configuration File
; Target Core: Espressif ESP32 Dev Module
; ------------------------------------------------------------------------------

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs
board_build.partitions = default.csv

lib_ldf_mode = deep+

lib_deps =
    fastled/FastLED @ ^3.6.0
    https://github.com/tzapu/WiFiManager.git
    me-no-dev/AsyncTCP @ ^1.1.1
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    bblanchon/ArduinoJson @ ^7.0.4
    ayushsharma82/ElegantOTA @ ^3.1.7

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1

[env:esp32dev_ota]
extends = env:esp32dev

upload_protocol = espota
upload_port = ledstrip-pixel.local
upload_flags =
    --port=3232